services:
  - type: web
    plan: free
    name: web
    runtime: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    dockerfilePath: ./Dockerfile.web
    envVars:
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
    envFile: .env
    ports:
      - 3000

databases:
  - name: db
    plan: free
    envVars:
      - key: POSTGRES_USER
        fromFile: .env
      - key: POSTGRES_PASSWORD
        fromFile: .env
      - key: POSTGRES_DB
        fromFile: .env
    volumes:
      - path: /var/lib/postgresql/data
        name: full_demo

envVars:
  # Generates a base64-encoded 256-bit value
  # (unless a value already exists)
  - key: SESSION_SECRET
    generateValue: true

  - key: POSTGRES_PASSWORD
    value: pwd

  - key: POSTGRES_DB
    value: petsitting

  - key: POSTGRES_USER
    value: postgres

  # References a property of a database
  # (see available properties below)
  - key: DATABASE_URL
    fromDatabase:
      name: db
      property: connectionString

